spring:
  profiles:
      active: dev
        

---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: Hello ici le DEV



---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: Hello ici la Prod