spring:
  profiles:
      active: prod
        

---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: Hello DEV



---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: Hello PROD